on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-zmk-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-zmk-

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Zephyr export
        run: west zephyr-export

      # ---------- LEFT HALF ----------
      - name: Build Amalgamate Left
        run: |
          west build -s zmk/app -b nice_nano_v2 \
            -- -DSHIELD=amalgamate_left \
               -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Rename Left UF2
        run: cp build/zephyr/zmk.uf2 amalgamate_left.uf2

      - name: Upload Left Firmware
        uses: actions/upload-artifact@v4
        with:
          name: amalgamate_left
          path: amalgamate_left.uf2

      # ---------- RIGHT HALF ----------
      - name: Build Amalgamate Right
        run: |
          west build --pristine -s zmk/app -b nice_nano_v2 \
            -- -DSHIELD=amalgamate_right \
               -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Rename Right UF2
        run: cp build/zephyr/zmk.uf2 amalgamate_right.uf2

      - name: Upload Right Firmware
        uses: actions/upload-artifact@v4
        with:
          name: amalgamate_right
          path: amalgamate_right.uf2
